### ISSUE TITLE
Use API-Call for Home Assistant - Template variable error: 'value_json' is undefined when rendering '{{ value_json.Last_Scan }}'

### ISSUE THREAD

**Issue by gericho** [leiweibau/Pi.Alert#223]
After adding the sensor via the command line platform as the notes found [here](https://github.com/leiweibau/Pi.Alert/blob/d94f5fb7955f1c9abcba6cbd90bcdd51f7f415bc/docs/API-USAGE.md#use-api-call-for-home-assistant)

I realized running Home Assistant 2023.12.4, the platform must be configured differently to match the new format in particular from this:
```
sensor:
  - platform: command_line
    name: "PiAlert - Last Scan"
    command: curl -k -X POST -F 'api-key=yourApi-Key' -F 'get=system-status' https://[URL]/api/
    scan_interval: 200
    unique_id: pialert.status.lastscan
    value_template: '{{ value_json.Last_Scan }}'
```

to this (so maybe the manual needs some changes)

```
command line:
  - sensor:
      name: "PiAlert - Last Scan"
      command: "curl -k -X POST -F 'api-key=yourApi-Key' -F 'get=system-status' https://[URL]/api/"
      scan_interval: 200
      unique_id: pialert.status.lastscan
      value_template: '{{ value_json.Last_Scan }}'
```
BTW now all the sensors report UNKNOWN and this is what I found in the HA core log:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   666  100   341  100   325   330k   315k --:--:-- --:--:-- --:--:--  650k
2024-01-03 19:15:59.359 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.Last_Scan }}'
```
![pialert](https://github.com/leiweibau/Pi.Alert/assets/29167042/f72f2074-998d-4565-bacd-8f4305ad09b0)

and the /api/ file reposts 404

```
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 Not Found</title>
 </head>
 <body>
  <h1>404 Not Found</h1>
 </body>
</html>
```

Besides generating and including the current API key and server local HTTP IP address in the sensor definition, I really don't know how to check if the API is rendering the correct JSON values. May I have some help? Thank you!
